import { readdir, readFile, writeFile, stat } from 'node:fs/promises';
import { join, relative, extname, basename } from 'node:path';

const SKIP_DIRS = new Set([
  'node_modules', '.next', '.git', 'dist', '.vercel',
  'coverage', '.turbo', '.cache',
]);

const SKIP_ARCHIVE = 'agents/archive';

const CODE_EXTENSIONS = new Set([
  '.ts', '.tsx', '.js', '.jsx', '.css', '.json', '.md',
  '.py', '.go', '.rs', '.sh',
]);

interface FileEntry {
  path: string;
  exports: string[];
  isRoute: boolean;
  routePath?: string;
}

export async function generatePin(
  projectRoot: string,
  outputFile: string,
): Promise<void> {
  const entries: FileEntry[] = [];

  await walkDir(projectRoot, projectRoot, entries);

  const pin = buildPinDocument(entries, projectRoot);
  await writeFile(outputFile, pin, 'utf-8');
}

async function walkDir(
  dir: string,
  projectRoot: string,
  entries: FileEntry[],
): Promise<void> {
  const items = await readdir(dir, { withFileTypes: true });

  for (const item of items) {
    const fullPath = join(dir, item.name);
    const relPath = relative(projectRoot, fullPath);

    if (item.isDirectory()) {
      if (SKIP_DIRS.has(item.name)) continue;
      if (relPath.startsWith(SKIP_ARCHIVE)) continue;
      await walkDir(fullPath, projectRoot, entries);
      continue;
    }

    if (!item.isFile()) continue;
    const ext = extname(item.name);
    if (!CODE_EXTENSIONS.has(ext)) continue;

    const entry: FileEntry = {
      path: relPath,
      exports: [],
      isRoute: false,
    };

    // Check if it's a Next.js route
    if (relPath.includes('src/app/') || relPath.includes('app/')) {
      const routeFiles = ['page.tsx', 'page.ts', 'layout.tsx', 'layout.ts', 'route.ts', 'route.tsx'];
      if (routeFiles.includes(item.name)) {
        entry.isRoute = true;
        const routeDir = relative(projectRoot, dir);
        entry.routePath = '/' + routeDir
          .replace(/^src\/app\/?/, '')
          .replace(/^app\/?/, '')
          .replace(/\(.*?\)\/?/g, '');
        if (entry.routePath === '/') entry.routePath = '/';
      }
    }

    // Extract exports from TS/JS files
    if (['.ts', '.tsx', '.js', '.jsx'].includes(ext)) {
      try {
        const content = await readFile(fullPath, 'utf-8');
        entry.exports = extractExports(content);
      } catch {
        // Skip unreadable files
      }
    }

    entries.push(entry);
  }
}

function extractExports(content: string): string[] {
  const exports: string[] = [];
  const patterns = [
    /export\s+(?:default\s+)?(?:function|class|const|let|var|interface|type|enum)\s+(\w+)/g,
    /export\s+default\s+(\w+)/g,
  ];

  for (const pattern of patterns) {
    for (const match of content.matchAll(pattern)) {
      if (match[1] && !exports.includes(match[1])) {
        exports.push(match[1]);
      }
    }
  }

  return exports;
}

function buildPinDocument(entries: FileEntry[], projectRoot: string): string {
  const lines: string[] = [
    '# Codebase Index (Pin)',
    '',
    `> Auto-generated by Wyvern pin-generator. Last updated: ${new Date().toISOString()}`,
    `> Project root: ${projectRoot}`,
    '',
  ];

  // Routes section
  const routes = entries.filter(e => e.isRoute);
  if (routes.length > 0) {
    lines.push('## Routes', '');
    lines.push('| Route | File | Type |');
    lines.push('|-------|------|------|');
    for (const r of routes) {
      const type = basename(r.path).replace(extname(r.path), '');
      lines.push(`| \`${r.routePath}\` | \`${r.path}\` | ${type} |`);
    }
    lines.push('');
  }

  // File tree by directory
  const dirMap = new Map<string, FileEntry[]>();
  for (const entry of entries) {
    const parts = entry.path.split('/');
    const dir = parts.length > 1 ? parts.slice(0, -1).join('/') : '.';
    const group = dirMap.get(dir) ?? [];
    group.push(entry);
    dirMap.set(dir, group);
  }

  lines.push('## File Index', '');
  const sortedDirs = [...dirMap.keys()].sort();
  for (const dir of sortedDirs) {
    const files = dirMap.get(dir)!;
    lines.push(`### \`${dir}/\``, '');
    for (const file of files) {
      const name = basename(file.path);
      const exportStr = file.exports.length > 0
        ? ` — exports: \`${file.exports.join('`, `')}\``
        : '';
      lines.push(`- \`${name}\`${exportStr}`);
    }
    lines.push('');
  }

  // Keyword index
  const keywords = new Map<string, string[]>();
  for (const entry of entries) {
    for (const exp of entry.exports) {
      const paths = keywords.get(exp) ?? [];
      paths.push(entry.path);
      keywords.set(exp, paths);
    }
  }

  if (keywords.size > 0) {
    lines.push('## Keyword Index', '');
    const sorted = [...keywords.entries()].sort(([a], [b]) => a.localeCompare(b));
    for (const [keyword, paths] of sorted) {
      lines.push(`- **${keyword}** → ${paths.map(p => `\`${p}\``).join(', ')}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}
