/**
 * research-pipeline.ts — Wyvern profile for ML/research validation projects.
 *
 * General-purpose profile for any project where the work
 * is: load data, run computations, produce artifacts (JSON, parquet, reports),
 * validate results against expected values.
 *
 * Key differences from web-app:
 *   - Verify = "does it run without error and produce valid artifacts"
 *   - Pin = Python modules, scripts, data sources, artifact locations
 *   - Longer watchdog timeout (research tasks are compute-heavy)
 *   - Spec sections: Experiments, Data Sources, Pipeline Stages
 */

import { readdir, readFile, stat } from 'node:fs/promises';
import { join, extname, relative } from 'node:path';
import type { WyvernProfile, ProfileLintRule, SpecSectionParser } from './profile.js';
import type { LintIssue } from '../engine/types.js';

// ─── Pin Generation ────────────────────────────────────────────

async function walkPython(dir: string, root: string): Promise<string[]> {
  const entries: string[] = [];
  try {
    const items = await readdir(dir, { withFileTypes: true });
    for (const item of items) {
      const fullPath = join(dir, item.name);
      // Skip venvs, caches, node_modules
      if (item.isDirectory()) {
        if (['__pycache__', 'node_modules', '.git', 'venv', '.venv', 'env'].includes(item.name)) continue;
        entries.push(...await walkPython(fullPath, root));
      } else if (item.isFile() && (extname(item.name) === '.py' || extname(item.name) === '.sh')) {
        entries.push(relative(root, fullPath));
      }
    }
  } catch { /* directory not readable */ }
  return entries;
}

async function extractDocstring(filePath: string): Promise<string | null> {
  try {
    const content = await readFile(filePath, 'utf-8');
    // Triple-quote docstring at module level
    const match = content.match(/^(?:#[^\n]*\n)*\s*(?:"""([\s\S]*?)"""|'''([\s\S]*?)''')/);
    if (match) {
      const doc = (match[1] ?? match[2]).trim();
      return doc.split('\n')[0]; // First line only
    }
    // Fall back to first comment block
    const commentMatch = content.match(/^#\s*(.+)/m);
    return commentMatch ? commentMatch[1].trim() : null;
  } catch {
    return null;
  }
}

async function generateResearchPin(projectRoot: string): Promise<string> {
  const files = await walkPython(projectRoot, projectRoot);
  const lines: string[] = [
    '# Codebase Index (auto-generated by Wyvern)',
    '',
    '## Python Scripts',
    '',
  ];

  // Group by directory
  const byDir = new Map<string, string[]>();
  for (const f of files) {
    const dir = f.includes('/') ? f.split('/').slice(0, -1).join('/') : '.';
    const list = byDir.get(dir) ?? [];
    list.push(f);
    byDir.set(dir, list);
  }

  for (const [dir, dirFiles] of Array.from(byDir.entries()).sort()) {
    lines.push(`### ${dir === '.' ? 'Root' : dir}`);
    for (const f of dirFiles.sort()) {
      const fullPath = join(projectRoot, f);
      const doc = await extractDocstring(fullPath);
      lines.push(doc ? `- \`${f}\` — ${doc}` : `- \`${f}\``);
    }
    lines.push('');
  }

  // Artifact directories
  lines.push('## Artifact Directories', '');
  const artifactDirs = ['phase1_artifacts', 'phase2_artifacts', 'results', 'output', 'artifacts'];
  for (const d of artifactDirs) {
    try {
      const s = await stat(join(projectRoot, d));
      if (s.isDirectory()) {
        const contents = await readdir(join(projectRoot, d));
        const jsonFiles = contents.filter(f => f.endsWith('.json'));
        const mdFiles = contents.filter(f => f.endsWith('.md'));
        lines.push(`- \`${d}/\` — ${contents.length} files (${jsonFiles.length} JSON, ${mdFiles.length} MD)`);
      }
    } catch { /* doesn't exist */ }
  }

  lines.push('');

  // Data sources (look for HuggingFace references)
  lines.push('## Data Sources', '');
  const claudeMd = join(projectRoot, 'CLAUDE.md');
  try {
    const content = await readFile(claudeMd, 'utf-8');
    const hfMatches = content.matchAll(/`([a-zA-Z0-9_-]+\/[a-zA-Z0-9_-]+)`.*?on HuggingFace/g);
    for (const m of hfMatches) {
      lines.push(`- HuggingFace: \`${m[1]}\``);
    }
  } catch { /* no CLAUDE.md */ }

  return lines.join('\n');
}

// ─── Lint Rules ────────────────────────────────────────────────

const verifyAcceptsPython: ProfileLintRule = {
  name: 'verify-accepts-python',
  check(content: string): LintIssue[] {
    const issues: LintIssue[] = [];
    const verifyMatch = content.match(/### Verify\s*\n([\s\S]*?)(?=\n###|\n$|$)/i);
    if (verifyMatch) {
      const verifyBlock = verifyMatch[1];
      const hasCommand = /\b(python|pytest|bash|sh|diff|jq|cat)\b/.test(verifyBlock);
      if (!hasCommand && !/```/.test(verifyBlock)) {
        issues.push({
          rule: 'verify-accepts-python',
          message: 'Verify block has no recognizable Python/bash commands. Expected python, pytest, bash, diff, or similar.',
          severity: 'warning',
        });
      }
    }
    return issues;
  },
};

const artifactOutputCheck: ProfileLintRule = {
  name: 'artifact-output-path',
  check(content: string): LintIssue[] {
    const issues: LintIssue[] = [];
    // Warn if prompt mentions writing to a path but doesn't verify the file exists
    const writesArtifact = /(?:write|save|output|produce).*?(?:\.json|\.parquet|\.csv|\.pkl|\.md)/i.test(content);
    const verifiesExistence = /(?:ls|test -f|stat|os\.path\.exists|Path\(.*\)\.exists)/i.test(content);
    if (writesArtifact && !verifiesExistence) {
      issues.push({
        rule: 'artifact-output-path',
        message: 'Prompt writes an artifact but verify section does not check the file exists.',
        severity: 'warning',
      });
    }
    return issues;
  },
};

// ─── Spec Section Parsers ──────────────────────────────────────

interface Experiment {
  name: string;
  hypothesis: string;
  scripts: string[];
  artifacts: string[];
  passCondition: string;
}

interface DataSource {
  name: string;
  location: string;
  format: string;
  size?: string;
}

function parseExperiments(body: string): Experiment[] {
  const experiments: Experiment[] = [];
  const blocks = body.split(/^##\s+/m).filter(Boolean);
  for (const block of blocks) {
    const lines = block.split('\n');
    const name = lines[0].trim();
    if (!name) continue;

    let hypothesis = '';
    const scripts: string[] = [];
    const artifacts: string[] = [];
    let passCondition = '';

    for (const line of lines.slice(1)) {
      const hypoMatch = line.match(/^-\s+hypothesis:\s*(.+)/i);
      if (hypoMatch) { hypothesis = hypoMatch[1].trim(); continue; }
      const scriptMatch = line.match(/^-\s+script:\s*(.+)/i);
      if (scriptMatch) { scripts.push(scriptMatch[1].trim()); continue; }
      const artifactMatch = line.match(/^-\s+artifact:\s*(.+)/i);
      if (artifactMatch) { artifacts.push(artifactMatch[1].trim()); continue; }
      const passMatch = line.match(/^-\s+pass:\s*(.+)/i);
      if (passMatch) { passCondition = passMatch[1].trim(); continue; }
    }

    experiments.push({ name, hypothesis, scripts, artifacts, passCondition });
  }
  return experiments;
}

function parseDataSources(body: string): DataSource[] {
  const sources: DataSource[] = [];
  const blocks = body.split(/^##\s+/m).filter(Boolean);
  for (const block of blocks) {
    const lines = block.split('\n');
    const name = lines[0].trim();
    if (!name) continue;

    let location = '';
    let format = '';
    let size: string | undefined;

    for (const line of lines.slice(1)) {
      const locMatch = line.match(/^-\s+location:\s*(.+)/i);
      if (locMatch) { location = locMatch[1].trim(); continue; }
      const fmtMatch = line.match(/^-\s+format:\s*(.+)/i);
      if (fmtMatch) { format = fmtMatch[1].trim(); continue; }
      const sizeMatch = line.match(/^-\s+size:\s*(.+)/i);
      if (sizeMatch) { size = sizeMatch[1].trim(); continue; }
    }

    sources.push({ name, location, format, size });
  }
  return sources;
}

const experimentsParser: SpecSectionParser = {
  sectionName: 'Experiments',
  parse: parseExperiments,
};

const dataSourcesParser: SpecSectionParser = {
  sectionName: 'Data Sources',
  parse: parseDataSources,
};

// ─── Profile Export ────────────────────────────────────────────

export const researchPipelineProfile: WyvernProfile = {
  name: 'research-pipeline',
  description: 'ML/research validation projects. Python scripts, HuggingFace data, JSON/parquet artifacts.',

  defaultVerifyCommands: [
    'python -m py_compile ${file}',
    'python ${file}',
  ],

  generatePin: generateResearchPin,

  lintRules: [verifyAcceptsPython, artifactOutputCheck],

  specSections: [experimentsParser, dataSourcesParser],

  defaults: {
    defaultModel: 'sonnet',
    watchdogTimeout: 1800,       // 30 min — research tasks are compute-heavy
    parallelTasksPerGate: 2,     // conservative — research scripts are memory-hungry
    maxPromptLines: { min: 8, max: 120 },
    verifyCommands: ['python -m pytest', 'python -c "print(\'verify passed\')"'],
    modelConfig: {
      opus:   { maxPromptLines: { min: 8,  max: 120 } },
      sonnet: { maxPromptLines: { min: 8,  max: 150 } },
      haiku:  { maxPromptLines: { min: 4,  max: 80  } },
    },
  },
};
