/**
 * web-app.ts — Wyvern profile for web application projects.
 *
 * The original Wyvern target. React/Next.js/FastAPI apps with
 * npm build pipelines, JS/TS exports, route-based navigation.
 *
 * This profile extracts the web-specific logic that was previously
 * hardcoded in the Wyvern engine. The engine is now project-agnostic;
 * all web-app assumptions live here.
 */

import { readdir, readFile, stat } from 'node:fs/promises';
import { join, extname, relative } from 'node:path';
import type { WyvernProfile, ProfileLintRule, SpecSectionParser } from './profile.js';
import type { LintIssue } from '../engine/types.js';

// ─── Pin Generation ────────────────────────────────────────────

async function walkTS(dir: string, root: string): Promise<string[]> {
  const entries: string[] = [];
  try {
    const items = await readdir(dir, { withFileTypes: true });
    for (const item of items) {
      const fullPath = join(dir, item.name);
      if (item.isDirectory()) {
        if (['node_modules', '.next', '.git', 'dist', 'build', '.turbo'].includes(item.name)) continue;
        entries.push(...await walkTS(fullPath, root));
      } else if (item.isFile()) {
        const ext = extname(item.name);
        if (['.ts', '.tsx', '.js', '.jsx'].includes(ext)) {
          entries.push(relative(root, fullPath));
        }
      }
    }
  } catch { /* directory not readable */ }
  return entries;
}

async function extractExports(filePath: string): Promise<string[]> {
  try {
    const content = await readFile(filePath, 'utf-8');
    const exports: string[] = [];
    const patterns = [
      /export\s+(?:default\s+)?(?:function|class|const|let|var|type|interface)\s+(\w+)/g,
      /export\s+\{([^}]+)\}/g,
    ];
    for (const pattern of patterns) {
      for (const match of content.matchAll(pattern)) {
        if (match[1]) {
          exports.push(...match[1].split(',').map(s => s.trim().split(/\s/)[0]).filter(Boolean));
        }
      }
    }
    return exports;
  } catch {
    return [];
  }
}

async function generateWebAppPin(projectRoot: string): Promise<string> {
  const files = await walkTS(projectRoot, projectRoot);
  const lines: string[] = [
    '# Codebase Index (auto-generated by Wyvern)',
    '',
  ];

  // Routes (Next.js app router convention)
  const routeFiles = files.filter(f => f.includes('/app/') && /page\.(tsx?|jsx?)$/.test(f));
  if (routeFiles.length > 0) {
    lines.push('## Routes', '');
    for (const f of routeFiles.sort()) {
      const route = f.replace(/^src\/app/, '').replace(/\/page\.\w+$/, '') || '/';
      lines.push(`- \`${route}\` → \`${f}\``);
    }
    lines.push('');
  }

  // File index with exports
  lines.push('## Files', '');
  const byDir = new Map<string, string[]>();
  for (const f of files) {
    const dir = f.includes('/') ? f.split('/').slice(0, -1).join('/') : '.';
    const list = byDir.get(dir) ?? [];
    list.push(f);
    byDir.set(dir, list);
  }

  for (const [dir, dirFiles] of Array.from(byDir.entries()).sort()) {
    lines.push(`### ${dir}`);
    for (const f of dirFiles.sort()) {
      const exports = await extractExports(join(projectRoot, f));
      const exportStr = exports.length > 0 ? ` — exports: ${exports.join(', ')}` : '';
      lines.push(`- \`${f}\`${exportStr}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ─── Lint Rules ────────────────────────────────────────────────

const verifyHasBuildCommand: ProfileLintRule = {
  name: 'verify-has-build',
  check(content: string): LintIssue[] {
    const issues: LintIssue[] = [];
    const verifyMatch = content.match(/### Verify\s*\n([\s\S]*?)(?=\n###|\n$|$)/i);
    if (verifyMatch) {
      const block = verifyMatch[1];
      const hasBuild = /\b(npm|npx|yarn|pnpm|bun|tsc|vite|next)\b/.test(block);
      if (!hasBuild && !/```/.test(block)) {
        issues.push({
          rule: 'verify-has-build',
          message: 'Verify block has no recognizable build command (npm, yarn, tsc, etc.).',
          severity: 'warning',
        });
      }
    }
    return issues;
  },
};

// ─── Spec Section Parsers ──────────────────────────────────────
// (Entities, Pages, Routes, Integrations — extracted from the
// original wyvern.ts parseEntities/parsePages/etc.)

const entitiesParser: SpecSectionParser = {
  sectionName: 'Entities',
  parse(body: string): unknown {
    // Delegates to the existing parser in swarm/wyvern.ts
    // This is a placeholder — the full implementation lives there
    return { _note: 'See swarm/wyvern.ts parseEntities for full implementation' };
  },
};

const pagesParser: SpecSectionParser = {
  sectionName: 'Pages',
  parse(body: string): unknown {
    return { _note: 'See swarm/wyvern.ts parsePages for full implementation' };
  },
};

// ─── Profile Export ────────────────────────────────────────────

export const webAppProfile: WyvernProfile = {
  name: 'web-app',
  description: 'Web applications. React/Next.js/FastAPI with npm build pipelines.',

  defaultVerifyCommands: [
    'npm run build',
    'npm run lint',
  ],

  generatePin: generateWebAppPin,

  lintRules: [verifyHasBuildCommand],

  specSections: [entitiesParser, pagesParser],

  defaults: {
    defaultModel: 'opus',
    watchdogTimeout: 900,
    parallelTasksPerGate: 4,
    maxPromptLines: { min: 8, max: 80 },
    verifyCommands: ['npm run build', 'npm run lint'],
    modelConfig: {
      opus:   { maxPromptLines: { min: 8,  max: 80  } },
      sonnet: { maxPromptLines: { min: 8,  max: 120 } },
      haiku:  { maxPromptLines: { min: 4,  max: 60  } },
    },
  },
};
